site_name: Tutoriales para el Grado de Videojuegos
theme:
  name: material
  font: 
    text: Inclusive Sans
    code: Chivo Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
    - content.action.edit
    - content.action.view
  language: es
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: slate
      toggle:
        icon: material/lightbulb-on
        name: light
      primary: slate
      accent: indigo
      
    - media: '(prefers-color-scheme: dark)'
      scheme: default
      toggle:
        icon: material/moon-waxing-crescent
        name: dark
      primary: blue
      accent: light blue
      

markdown_extensions:
  - toc:
      permalink: true
      separator: "_"
      title: "Tabla de contenidos"
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

repo_url: https://github.com/JesusJMUJI/jesusjm-website
repo_name: Tutoriales Grado Videojuegos
edit_uri: edit/main/docs/

copyright: |
  &copy; 2023 <a href="https://github.com/JesusJMUJI"  target="_blank" rel="noopener">Jesús JM</a>

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
