site_name: Jesus Website
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: dark
      primary: blue
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: light
      primary: slate
      accent: indigo

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

copyright: |
  &copy; 2023 <a href="https://github.com/JesusJMUJI"  target="_blank" rel="noopener">Jesús JM</a>