site_name: Tutoriales para el Grado de Videojuegos
theme:
  name: material
  font: 
    text: Lexend Deca # Inter Tight
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    # - toc.integrate
    - toc.follow
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
  language: es
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: slate
      toggle:
        icon: material/lightbulb-on
        name: light
      primary: deep purple
      accent: indigo
      
    - media: '(prefers-color-scheme: dark)'
      scheme: default
      toggle:
        icon: material/moon-waxing-crescent
        name: dark
      primary: blue
      accent: light blue


markdown_extensions:
  - toc:
      permalink: true
      title: "Tabla de contenidos"
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true

repo_url: https://github.com/JesusJMUJI/jesusjm-website
repo_name: Tutoriales Grado Videojuegos
edit_uri: edit/main/docs/

copyright: |
  &copy; 2023 <a href="https://github.com/JesusJMUJI"  target="_blank" rel="noopener">Jesús JM</a>

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox

nav:
  - Página Principal: index.md
  - Latex: 
      - Introducción a LaTeX: latex_index.md
      - Instalación de LaTeX con Miktex y TexStudio: latex_install.md
      - Instalación de LaTeX con VSCode y MikTex : latex_vscode.md

